// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComponentFooter: typeof import('./src/components/component-footer.vue')['default']
    ComponentHeader: typeof import('./src/components/component-header.vue')['default']
    CreateEventModal: typeof import('./src/components/create-event-modal/index.vue')['default']
    CreateEventModalAtomEventForm: typeof import('./src/components/create-event-modal/atom-event-form.vue')['default']
    CreateEventModalBasic: typeof import('./src/components/create-event-modal/basic.vue')['default']
    CreateEventModalCollectionEventForm: typeof import('./src/components/create-event-modal/collection-event-form.vue')['default']
    EventDetail: typeof import('./src/components/event-detail/index.vue')['default']
    PickersRangePicker: typeof import('./src/components/pickers/range-picker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status: typeof import('./src/components/status.vue')['default']
  }
}
