// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CharaBadge: typeof import('./src/components/chara-badge.vue')['default']
    CharaBadgeTable: typeof import('./src/components/chara-badge-table.vue')['default']
    CharaDetailCard: typeof import('./src/components/chara-detail-card.vue')['default']
    CharaItem: typeof import('./src/components/chara-item.vue')['default']
    ComponentFooter: typeof import('./src/components/component-footer.vue')['default']
    ComponentHeader: typeof import('./src/components/component-header.vue')['default']
    CreateCharacterModal: typeof import('./src/components/create-character-modal.vue')['default']
    CreateEventModal: typeof import('./src/components/create-event-modal.vue')['default']
    EventContextMenu: typeof import('./src/components/event-context-menu.vue')['default']
    EventDetailCard: typeof import('./src/components/event-detail-card.vue')['default']
    EventDetailCardTrigger: typeof import('./src/components/event-detail-card-trigger.vue')['default']
    EventItem: typeof import('./src/components/event-item.vue')['default']
    ResizeLayout: typeof import('./src/components/resize-layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneItem: typeof import('./src/components/scene-item.vue')['default']
    Selector: typeof import('./src/components/selector.vue')['default']
    Status: typeof import('./src/components/status.vue')['default']
    UnitRangePicker: typeof import('./src/components/unit-range-picker.vue')['default']
    UnitTimePicker: typeof import('./src/components/unit-time-picker.vue')['default']
  }
}
